name: Deploy to EB
on:
  push:
    branches: [ master ]

jobs:
  buildAndTest:
    name: CI Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '14.x' ]

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

  deploy:
    name: CD Pipeline
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '14.x' ]

    needs: buildAndTest
    steps:
      - uses: actions/checkout@v2
      - name: Make .env file
        run: |
          echo "AWS_REGION=$AWS_REGION" >> .env
          echo "AWS_S3_BUCKET_NAME=$AWS_S3_BUCKET_NAME" >> .env
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
          echo "DATABASE=$DATABASE" >> .env
          echo "HOST=$HOST" >> .env
          echo "NEST_PORT=$NEST_PORT" >> .env
          echo "PASSWORD=$PASSWORD" >> .env
          echo "USERNAME=$USERNAME" >> .env
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DATABASE: ${{ secrets.DATABASE }}
          HOST: ${{ secrets.HOST }}
          NEST_PORT: ${{ secrets.NEST_PORT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USERNAME: ${{ secrets.USERNAME }}

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Copy to NCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: './*'
          target: 'server'

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd server
            touch log.txt
            npm run start > log.txt &

//test           
name: Deploy to NAVER storage
on:
  push:
    branches: [ master ]

jobs:
  buildAndTest:
    name: CI Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '14.x' ]

    steps:
      - uses: actions/checkout@v2

      # - name: Install Node.JS ${{ matrix.node-version }}
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run build
        run: yarn run build