name: Deploy to NCP Object Storage
on:
  push:
    branches:
      - master

jobs:
  buildAndTest:
    name: CI Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '14.x' ]

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Make .env file
        run: |
          echo "REACT_APP_NAVER_CLIENT_ID=$NAVER_CLIENT_ID" >> .env
          echo "REACT_APP_NAVER_CALLBACK_URL=$NAVER_CALLBACK_URL" >> .env
          echo "REACT_APP_API" >> .env
        env:
          REACT_APP_NAVER_CLIENT_ID: ${{ secrets.REACT_APP_NAVER_CLIENT_ID }}
          REACT_APP_NAVER_CLIENT_SECRET: ${{ secrets.REACT_APP_NAVER_CLIENT_SECRET }}
          REACT_APP_API: ${{ secrets.REACT_APP_API }}    

      - name: Install dependencies
        run: yarn

      - name: Install env-cmd
        run: yarn add global env-cmd

      - name: Run build
        env:
          CI: ""
        run: yarn build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: >
          aws s3 cp --endpoint-url=https://kr.object.ncloudstorage.com --recursive --region kr-standard build s3://${{ secrets.AWS_STORAGE_NAME }}