name: Deploy to NCP Object Storage
on:
  push:
    branches:
      - master

jobs:
  buildAndTest:
    name: CI Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '14.x' ]

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Run build
        run: yarn build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        run: |
          aws
            --endpoint-url=https://kr.object.ncloudstorage.com
            s3 cp \
            --recursive \
            --region kr-standard \
            build \ 
            s3://${{ secrets.AWS_STORAGE_NAME }}